name: Move new issues into Triage

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Issues and Change Requests
          column: Inbox
          repo-token: ${{ secrets.GITHUB_TOKEN }}
